trigger: none
pr: none
pool:
  vmImage: ubuntu-latest

jobs:
  - job: calculateSemVer
    displayName: Calculate SemVer

    steps:
      - checkout: self
        fetchDepth: 0

      - task: gitversion/setup@0
        inputs:
          versionSpec: '6.0.x'

      - task: gitversion/execute@0
        inputs:
          useConfigFile: true
          configFilePath: GitVersion.yml
